/** Kotoba's Japanese language pack; untranslated extension keys fall back to English. */
export const japanese: Record<string, Record<string, string>> = {
  common: {
    ok: 'OK', cancel: 'キャンセル', close: '閉じる', copy: 'コピー', copied: 'コピーしました',
    'copy.failed': 'コピーできませんでした', 'copy.value': '値をコピー', 'copy.json': 'JSON をコピー',
    'copy.path': 'プロパティのパスをコピー', 'copy.prettyJson': '整形した JSON をコピー',
    'copy.compactJson': '圧縮した JSON をコピー', 'copy.optionsHint': '{action}；右クリックでコピーの形式を選択',
    retry: '再試行', loading: '読み込み中…', 'load.failed': '読み込めませんでした', submit: '送信',
    submitting: '送信中…', next: '次へ', previous: '前へ', skip: 'スキップ', delete: '削除',
    edit: '編集', save: '保存', search: '検索', more: 'その他', collapse: '折りたたむ', expand: '展開',
    back: '戻る', 'brand.localBuild': 'Kotoba Studio', unknown: '不明', none: 'なし', truncated: '省略あり',
    'json.collapseNode': 'JSON ノードを折りたたむ', 'json.expandNode': 'JSON ノードを展開', 'json.label': 'JSON',
    'markdown.footnotes': '脚注', 'markdown.truncatedCharacters': '… {total} 文字で省略',
    'number.thousand': '{value}K', 'number.million': '{value}M',
  },
  sidebar: {
    'session.new': '新しい会話', 'session.new.label': '新しい会話',
    'toggle.open': 'サイドバーを開く', 'toggle.collapse': 'サイドバーを閉じる',
  },
  'settings.locale': { 'language.title': '表示言語' },
  'settings.theme': {
    'appearance.title': '外観', 'appearance.light': 'ライト', 'appearance.dark': 'ダーク',
    'appearance.system': 'システム設定', 'fontSize.title': '文字サイズ', 'fontSize.description': '会話本文に適用します',
    'fontSize.unit': 'px', 'fontSize.increase': '文字を大きくする', 'fontSize.decrease': '文字を小さくする',
  },
  settings: {
    trigger: '設定', title: '設定', close: '閉じる', openDocument: '設定ファイルを開く',
    'openDocument.error': '設定ファイルを開けませんでした', 'general.nav': '一般',
    'connection.error': '接続が切れました', 'connection.retry': '再接続', 'connection.connecting': '再接続中',
    'connection.connected': '接続済み', 'connection.reconnect': '接続が切れました。クリックして再接続',
    'connection.restart': '自動再接続中。クリックして再試行',
  },
  model: {
    'provider.select': 'API プロバイダーを選択',
    'provider.aria': 'API プロバイダーを選択、現在 {provider}',
    'provider.ready': '設定済み', 'provider.setup': '設定が必要',
    'command.description': 'この会話で使用するモデルを選択', 'option.loadError': '一覧を読み込めませんでした：{message}',
    'trigger.fallback': 'モデルを選択', 'trigger.loading': 'モデルを読み込み中…', 'trigger.selectAria': 'モデルを選択',
    'trigger.aria': 'モデルを選択、現在：{model}', 'trigger.ariaEffort': 'モデルを選択、現在：{model}、推論レベル：{effort}',
    'menu.aria': 'モデルと推論レベル', 'menu.model': 'モデル', 'menu.effort': '推論レベル',
    'effort.providerDefault': '既定', 'status.loading': 'モデル一覧を更新中…',
    'error.action': 'モデルの操作に失敗しました：{message}', 'action.reload': '再読み込み',
    'warning.groupLoad': '{name} を読み込めませんでした：{message}', 'empty.models': '利用可能なモデルがありません。',
    'blocked.composer': 'このモデルは利用できません。モデルを選択してください',
    'empty.efforts': 'このモデルには推論レベルの設定がありません。',
  },
  'directory-browser': {
    'browser.title': '作業フォルダーを選択', 'browser.home': 'ホーム',
    'browser.newFolder': '新しいフォルダー', 'browser.folderName': 'フォルダー名',
    'browser.createIn': '「{name}」にフォルダーを作成', 'browser.untitledFolder': '新しいフォルダー',
    'browser.create': '作成', 'browser.cancel': 'キャンセル', 'browser.open': '開く',
    'browser.editPath': 'パスを編集', 'browser.loading': '読み込み中…',
    'browser.truncated': 'フォルダーが多いため、一部のみ表示しています。',
    'browser.showHidden': '隠しファイルを表示',
  },
  workspace: {
    'group.ungrouped': '未分類', 'session.new': '新しい会話', 'section.workspaces': 'ワークスペース',
    'section.sessions': '会話', 'viewOptions.label': '表示オプション', 'groupBy.label': 'グループ分け',
    'groupBy.workspace': 'ワークスペース別', 'groupBy.flat': '一覧表示', 'orderBy.label': '並べ替え',
    'orderBy.manual': '手動', 'orderBy.updated': '最終更新', 'sessions.expand': '残り {n} 件の会話を表示',
    'sessions.collapse': '表示を減らす', 'empty.none': 'まだ会話がありません', 'empty.noMatches': '一致する項目がありません',
    'workspace.add': 'ワークスペースを追加', 'search.sessions.aria': '会話を検索', 'search.placeholder': '会話を検索…',
    'search.clear': '検索をクリア', 'search.results.aria': '検索結果', 'search.pending': '会話履歴を検索中…',
    'search.unavailable': '本文検索を利用できません。名前の一致を表示します。', 'search.noMatches': '一致する会話がありません',
    'search.hasMore': '最初の {n} 件を表示しています。検索条件を絞ってください。', 'menu.addWorkspace': 'ワークスペースを追加…',
    'picker.loading': 'ワークスペースを読み込み中…', 'conflict.named': '「{name}」は既に存在します。',
    'folderError.title': 'フォルダーを開けませんでした', 'folderError.retry': '選び直す', rename: '名前を変更',
    'rename.workspace.title': 'ワークスペース名を変更', 'rename.session.title': '会話名を変更',
    'field.workspaceName': 'ワークスペース名', 'field.sessionName': '会話名', 'delete.workspace': 'ワークスペースを削除',
    'delete.desc': '一覧から「{name}」を削除します。フォルダーと会話履歴は保持され、会話は「未分類」に移動します。',
    'delete.pending': 'ワークスペースを削除中…', 'menu.fork': '会話を分岐', 'menu.archiveSession': '会話をアーカイブ',
    'sessions.count.one': '{n} 件の会話', 'sessions.count.other': '{n} 件の会話',
    'actions.workspace.aria': 'ワークスペース「{name}」の操作', 'actions.session.aria': '会話「{name}」の操作',
    'actions.newSession.aria': '「{name}」で新しい会話を開始', 'status.running': '実行中',
    'status.subagentsRunning.one': '{n} 個のサブエージェントが実行中', 'status.subagentsRunning.other': '{n} 個のサブエージェントが実行中',
    'status.idle': '待機中', 'status.waitingApproval': '承認待ち', 'status.planReview': '計画の確認待ち',
    'status.waitingAnswer': '回答待ち', 'status.completed': '完了', 'schedule.active': '有効なスケジュールがあります',
    'hover.created': '作成：{time}', 'hover.copied': 'コピーしました', 'date.ymd': '{y}年{m}月{d}日',
    'time.now': 'たった今', 'time.minutes': '{n}分', 'time.hours': '{n}時間', 'time.days': '{n}日',
    'time.months': '{n}か月', 'time.years': '{n}年', 'time.ago': '{t}前',
  },
  chat: {
    'view.chat': 'チャット', 'number.groupSeparator': ',', 'duration.compactSeconds': '{seconds}秒',
    'duration.compactMinutes': '{minutes}分{seconds}秒', 'duration.milliseconds': '{milliseconds}ミリ秒',
    'stats.counts': '{turns} ターン・{steps} ステップ', 'stats.cacheHit': 'キャッシュヒット {percent}%',
    'stats.dialog.title': '会話の統計', 'stats.dialog.usageTitle': 'トークン使用量', 'stats.dialog.llmTime': 'モデルの処理時間',
    'stats.dialog.toolTime': 'ツールの処理時間', 'stats.dialog.ttft': '最初のトークンまでの平均時間（TTFT）',
    'stats.dialog.speed': '出力速度（TPS）', 'chat.loadingHistory': '履歴を読み込み中…',
    'chat.loadError': '履歴を読み込めませんでした：{message}（{code}）', 'chat.loadOlder': '以前の履歴を読み込む',
    'chat.toBottom': '一番下へ', 'chat.deepDiving': '考えています…', 'chat.turnNavigation.label': 'ターンの移動',
    'chat.turnNavigation.jump': 'ターン {turn} に移動', 'chat.turnNavigation.jumpLoad': 'ターン {turn} を読み込んで移動',
    'chat.turnNavigation.turn': 'ターン {turn}', 'settings.transcript.title': '会話の表示',
    'settings.transcript.description': '完了したターンの処理内容の表示方法', 'settings.transcript.normal': '標準',
    'settings.transcript.compact': 'コンパクト', 'fileOpen.title': 'ファイルを開けませんでした', 'fileOpen.unknown': 'このファイルを開けません',
    'message.extraBlock': '追加の内容', 'message.systemPrompt': 'システムプロンプト', 'message.systemPromptUpdate': 'システムプロンプトの更新',
    'message.contextInjection': 'コンテキストの追加', 'message.contextRecall': '別の会話から参照', 'message.referenceSummary': '参照した会話 · {labels}',
    'message.referenceSeparator': '、', 'message.context.instructions.loaded': '読み込み済み',
    'message.context.instructions.added': '追加済み', 'message.context.instructions.updated': '更新済み',
    'message.context.instructions.removed': '削除済み', 'message.context.catalog.replaced': '一覧を置換',
    'message.context.catalog.more': '… 残り {count} 件', 'message.context.snapshot.supersedes': '以前のスナップショットを置換',
    'message.context.relay.from': '会話 {session} から', 'message.context.recall.counts': '{retained} 件保持・{omitted} 件省略',
    'message.context.recall.truncated': '省略あり', 'message.compaction': 'コンテキストを圧縮しました',
    'message.compaction.running': '圧縮中…', 'message.compaction.completed': '{items} 件の履歴を圧縮（約 {tokens} トークン）',
    'message.compaction.expand': 'クリックして要約を表示', 'message.compaction.unavailable': '要約を表示できません',
    'message.compaction.commandTitle': 'compact', 'message.think': '思考', 'message.unknownSurface': '不明な表示イベント：{type}',
    'message.unknownBlock': '不明な内容', 'message.turnProcess.toolCalls.one': 'ツール呼び出し {count} 回',
    'message.turnProcess.toolCalls.other': 'ツール呼び出し {count} 回', 'message.turnProcess.messages.one': 'メッセージ {count} 件',
    'message.turnProcess.messages.other': 'メッセージ {count} 件', 'message.turnProcess.subagents.one': 'サブエージェント {count} 個',
    'message.turnProcess.subagents.other': 'サブエージェント {count} 個', 'message.turnProcess.thoughtForAWhile': '思考完了',
    'message.turnProcess.separator': ' · ', 'message.stopped': '停止済み', 'message.branch': '新しい会話に分岐',
    'message.branchUnavailable': '完了したターンの最後のメッセージから分岐できます', 'message.retry.active': 'モデルへのリクエストを再試行中',
    'message.retry.cancelled': 'モデルへの再試行をキャンセルしました', 'message.retry.started': 'モデルへのリクエストを再試行しました',
    'message.retry.scheduled': 'モデルへの再試行を待機中', 'message.retry.status': '{label}（{retry}/{maximum}） · {seconds}秒',
    'message.retry.delay': '再試行まで：', 'message.retry.failure': '失敗の原因：', 'message.failure.auth': 'API キーが無効です',
    'message.turnError': 'このターンは失敗しました', 'message.maxTokens': '出力トークンの上限に達しました',
    'message.maxTokens.hint': '回答が途中で終了しました。出力は保持されています。「続けて」と送信すると続きを依頼できます。',
    'message.ranFor': '実行時間 {duration}', 'message.tokensPerSecond': '{tps} トークン/秒', 'message.turnUsage.title': 'このターンの使用量',
    'message.turnUsage.consumed': '使用量 {total}', 'message.turnUsage.model': 'プロバイダー / モデル',
    'message.turnUsage.cacheHit': 'キャッシュヒット', 'message.turnUsage.input': '未キャッシュの入力',
    'message.turnUsage.cacheRead': 'キャッシュ読み取り', 'message.turnUsage.cacheWrite': 'キャッシュ書き込み',
    'message.turnUsage.output': '出力', 'message.turnUsage.reasoning': '（うち推論 {tokens}）', 'message.turnUsage.count': '{count} トークン',
    'message.turnTime.title': 'このターンの時間と速度', 'message.turnTime.duration': '合計時間',
    'message.turnTime.speed': '出力速度（TPS）', 'message.turnTime.ttft': '最初のトークンまで（TTFT）',
    'duration.seconds': '{seconds}秒', 'duration.minutes': '{minutes}分{seconds}秒', 'command.running': '実行中…',
    'command.failed': 'コマンドが失敗しました', 'command.done': '完了', 'command.title': 'コマンド',
    'row.running': '実行中', 'row.failed': '失敗', 'json.truncated': '… 全 {total} 文字、一部省略',
    'clock.md': '{m}月{d}日', 'clock.ymd': '{y}年{m}月{d}日',
  },
  'settings.models': {
    nav: 'モデル', title: 'モデル', intro: 'API キーを設定するか、ローカルモデル画面で端末内のモデルを登録してください。',
    edit: '編集', editProvider: '{provider} を編集', remove: '削除', removeProvider: '{provider} を削除',
    deleteTitle: '{provider} を削除しますか？', deleteDescription: '{provider} の設定を削除します。別に管理されている認証情報は保持されます。',
    deleteDescriptionWithCredential: '{provider} の設定と保存された API キーを削除します。', deleteConfirm: '{provider} を削除',
    deleting: '{provider} を削除中…', add: 'プロバイダーを追加', provider: 'プロバイダー', close: '閉じる', cancel: 'キャンセル',
    apply: '適用', applying: '適用中…', savedProvider: '{provider} を保存しました。', credentialConfigured: 'API キー設定済み',
    credentialMissing: 'API キー未設定', readOnly: 'この環境では設定を変更できません。', loadFailed: 'プロバイダー一覧を読み込めませんでした',
    conflict: '編集中に設定が変更されました。閉じて開き直し、最新の値を編集してください。', retry: '再試行',
    keyInput: 'API キー', keyPlaceholder: 'API キーを入力', keyPlaceholderNative: 'API キーを入力するか、空欄で環境の認証情報を使用',
    keyStored: '設定済み — 新しい値で置き換え', keyEnvLocked: '起動時の環境から設定（読み取り専用）', customized: 'カスタム設定',
    baseUrl: 'ベース URL', baseUrlDefault: 'プロバイダーの既定値', models: 'モデル', modelsInherited: 'アダプターの既定値を使用',
    modelsCustomized: 'カスタムのモデル一覧', resetModels: '既定値に戻す', model: 'モデル', modelId: 'モデル ID', modelName: '表示名',
    modelNamePlaceholder: '空欄の場合はモデル ID を使用', contextWindow: 'コンテキスト長', contextWindowPlaceholder: 'プロバイダーの既定値を使用',
    maxTokens: '最大出力トークン数', maxTokensPlaceholder: 'プロバイダーの既定値を使用', modelAdvanced: '容量', addModel: 'モデルを追加',
    removeModel: 'モデルを削除', modelsEmpty: '選択欄に表示されるモデルがありません。一覧にない ID は直接指定できます。',
    keyBlank: 'API キーを入力してください。空欄の場合は保存済みのキーを保持します。',
    keyBlankNew: 'API キーを入力してください。他の認証方式を使用する場合は空欄にしてください。', keyIllegalCharacters: 'API キーの形式を確認してください。',
    modelIdRequired: 'モデル ID が必要です。', modelIdDuplicate: 'モデル ID が重複しています。', modelNameInvalid: '表示名を入力してください。',
    modelContextInvalid: 'コンテキスト長は正の数で指定してください（例：131072、256K、1M）。',
    modelMaxTokensInvalid: '最大出力トークン数は正の数で指定してください（例：8192、64K、1M）。',
    advancedHint: 'その他の項目は settings.yaml で直接編集できます。', modelCapacityInvalid: '数値で指定してください。K または M を付けられます。',
    modelDuplicate: 'モデル ID は一度だけ指定できます。', modelContextWindow: 'コンテキスト長', modelMaxTokens: '最大出力トークン数',
    fetchModels: '利用可能なモデルを取得', fetching: 'プロバイダーに問い合わせ中…', fetchNeedsBaseUrl: '先にベース URL を入力してください。',
    fetchEmpty: 'モデルが見つかりませんでした。手動で追加してください。', fetchTitle: '追加するモデルを選択',
    fetchDescription: 'プロバイダーが提供するモデルから、追加するものを選んでください。', fetchSearch: 'モデルを検索',
    fetchNoMatches: '一致するモデルがありません。', fetchSelectAll: 'すべて選択', fetchDeselectAll: '選択を解除', fetchAdopt: '選択したモデルを追加',
    customAdd: 'カスタムプロバイダーを追加', customTitle: 'カスタムプロバイダー', customTag: 'カスタム', customRoute: 'プロバイダー ID',
    customRouteHint: '小文字で始まる一意の識別子です。リクエストと認証情報の名前に使用します。',
    customRouteInvalid: '小文字で始め、小文字・数字・ハイフンを使用してください。', customRouteTaken: 'この ID は既に使用されています。',
    customDisplayName: '表示名', customApi: 'API プロトコル', customApiUnset: '未選択', customNeedsBaseUrl: 'ベース URL が必要です。',
    customNeedsModels: '1 つ以上のモデルが必要です。', customBaseUrlPlaceholder: 'https://gateway.example/v1',
    settingsPathUnresolvable: '設定のパスを解決できません', create: 'プロバイダーを作成', creating: '作成中…',
    welcomeTitle: '開発プレビュー', welcomeBody: 'Kotoba Studio へようこそ。', welcomeContinue: '続ける', welcomeError: '保存できませんでした。',
    onboardingTitle: '好きなモデルを、ひとつのワークスペースで。', onboardingDescription: 'OpenAI、Claude、Kimi、DeepSeek などのプロバイダーを接続して、Kotoba Studio で作業を始めましょう。',
    onboardingHint: 'API キーを保存したら、チャットで使うモデルを選んでください。「設定 → モデル」でプロバイダーを追加できます。ローカルモデルを使う場合は「後で設定」を選んでください。',
    providerOpenAI: 'OpenAI', providerClaude: 'Anthropic · Claude', providerKimi: 'Kimi · Moonshot AI',
    onboardingLater: '後で設定', onboardingSave: '保存して続ける', onboardingSaving: '保存中…', keyRequired: '続行するには API キーを入力してください。',
  },
  conversation: {
    'hint.plan': 'タスクを説明して計画を作成', 'hint.goal': '目標を入力すると、エージェントが継続して実行します',
    'hint.goal.active': '目標を実行中です。edit：編集 / pause：一時停止 / resume：再開 / clear：解除',
    'placeholder.plan': 'タスクを説明して計画を作成',
    'placeholder.default': 'メッセージやタスクを入力。/ でコマンド、@ でファイルや会話を参照',
    'placeholder.unavailable': 'この会話は利用できません',
    'placeholder.parentOffline': '親の会話がオフラインのため送信できません。現在の実行は停止できます',
    'placeholder.hero': '作りたいものを教えてください。/ でコマンド、@ でファイルや会話を参照',
    'placeholder.workspace': 'ワークスペースを選択して開始', 'placeholder.steerQueue': 'Cmd/Ctrl+Enter で待機中のメッセージを割り込み送信',
    'input.commands': 'コマンド', 'input.stop': '生成を停止', 'input.send': 'メッセージを送信',
    'input.send.queue': '送信待ちに追加', 'input.send.steer': '割り込み送信', 'input.accessMode': 'アクセス権限、現在：{name}',
    'attachment.pending': '送信待ちの添付', 'attachment.scrollLeft': '添付を左にスクロール',
    'attachment.scrollRight': '添付を右にスクロール', 'attachment.dropTitle': 'ファイルや画像をここにドロップ',
    'attachment.dropDesc': '画像：最大 {count} 枚、1 枚あたり {size}', 'attachment.dropBlocked': '現在、添付できません',
    'image.pending': '送信待ちの画像', 'image.openOriginal': '元の画像を開く', 'image.openOriginalLabel': '{label}、クリックして元の画像を表示',
    'image.remove': '画像 {name} を削除', 'image.original': '元の画像', 'image.label': '画像',
    'image.loadFailed': '画像を読み込めませんでした。クリックして再試行', 'image.loading': '画像を読み込み中…',
    'image.preview': '元の画像のプレビュー', 'image.closePreview': '画像のプレビューを閉じる',
    'image.unsupportedType': 'PNG、JPG、WebP、GIF 形式に対応しています', 'image.tooMany': '1 メッセージに最大 {count} 枚まで添付できます',
    'image.fileTooLarge': '1 枚の画像は {size} 以下にしてください', 'image.totalTooLarge': '画像の合計が {size} を超えています。一部を削除してください',
    'image.tooManyPixels': '画像の解像度が高すぎます。縮小してください', 'image.dimensionTooLarge': '画像の幅と高さは {size}px 以下にしてください',
    'image.modelUnsupported': 'このモデルは画像に対応していません。対応モデルに切り替えてください',
    'image.sendFailed': '画像を送信できませんでした（{reason}）。もう一度追加してください',
    'file.attach': 'ファイルを添付', 'file.pending': '送信待ちのファイル', 'file.remove': 'ファイル {name} を削除',
    'file.uploading': 'アップロード中…', 'file.uploadFailed': 'アップロードに失敗しました。クリックして再試行',
    'file.retry': '{name} のアップロードを再試行', 'file.stillUploading': 'アップロードの完了をお待ちください',
    'file.sessionUnavailable': '会話が利用できないためアップロードできません', 'file.notStaged': 'アップロードが完了していません。ファイルを追加し直してください',
    'file.label': 'ファイル', 'context.aria': 'コンテキスト使用量 {percent}', 'context.used': 'コンテキスト使用量',
    'context.system': 'システムプロンプト', 'context.tools': 'ツール定義', 'context.messages': '会話メッセージ',
    'settings.enter.title': '実行中の送信動作', 'settings.enter.description': '実行中の Enter キーと送信ボタンの動作。Cmd/Ctrl+Enter で別の動作を選べます',
    'settings.enter.queue': '送信待ちに追加', 'settings.enter.steer': '割り込み送信',
    'access.preset.readOnly': '閲覧のみ', 'access.preset.workspaceWrite': 'ワークスペース内の編集', 'access.preset.fullAccess': 'フルアクセス',
    'access.confirm.title': 'フルアクセスを有効にしますか？',
    'access.confirm.description': '確認を減らし、ファイルの変更や外部コマンドなどの操作を許可します。信頼できるタスクで使用してください。',
    'access.confirm.acknowledge': 'リスクを理解して続行します', 'access.confirm.cancel': 'キャンセル', 'access.confirm.enable': 'フルアクセスを有効にする',
    'hero.headline': 'ことばを、かたちに。', 'hero.preview': 'プレビュー', 'hero.chooseWorkspace': 'ワークスペースを選択',
    'session.hierarchy': '会話の階層', 'todo.title': 'タスク', 'todo.progress.done': '{done} 件完了',
    'todo.progress.active': '{active} 件実行中', 'todo.progress.pending': '{pending} 件待機中', 'todo.rowTitle': 'タスク一覧を更新',
    'todo.completed': '{done}/{total} 件完了', 'command.attachmentsUnsupported': '/{command} では添付を使用できません。添付を削除してください',
    'ask.rowTitle': '質問', 'ask.waiting': '回答待ち', 'ask.cancelled': 'キャンセル済み',
    'ask.cancelledDetail': 'キャンセルされたため回答は送信されませんでした', 'ask.interrupted': '中断済み',
    'ask.interruptedDetail': '中断されたため回答は送信されませんでした', 'ask.answered': '{answered}/{total} 件回答済み', 'ask.skipped': '未回答',
    'bash.running': '実行中', 'bash.failed': '失敗', 'bash.stopped': '停止済み', 'row.running': '実行中',
    'row.failed': '失敗', 'row.stopped': '停止済み', 'row.input': '入力', 'row.output': '出力', 'row.inspect': '詳細',
    'tool.title.search': '検索', 'tool.title.read': '読み取り', 'tool.title.bash': 'Bash', 'tool.title.write': '書き込み',
    'tool.title.edit': '編集', 'tool.title.code': 'コード', 'tool.title.generic': 'ツール呼び出し', 'tool.title.inspect': '詳細',
    'tool.title.runCordis': 'Cordis プラグインを実行', 'tool.title.stopCordis': 'Cordis プラグインを停止',
    'tool.title.removeCordis': 'Cordis プラグインを削除', 'tool.title.pwsh': 'PowerShell', 'tool.title.readImage': '画像を読み取り',
    'tool.title.grep': 'Grep', 'tool.title.glob': 'Glob', 'tool.title.webSearch': 'ウェブ検索', 'tool.title.webFetch': 'ウェブページを取得',
    'diff.files.one': '{count} ファイル', 'diff.files.other': '{count} ファイル', 'diff.collapseAria': '差分を折りたたむ',
    'diff.expandAria': '残り {count} 行の差分を展開', 'diff.expandRest': '… 残り {count} 行',
    'read.window': '{total} 行中 {shown} 行を表示', 'read.collapseAria': '内容を折りたたむ',
    'read.expandAria': '残り {count} 行を展開', 'read.expandRest': '… 残り {count} 行',
    'search.paths': '{shown} 件のパス', 'search.paths.truncated': '{total} 件中 {shown} 件のパスを表示',
    'search.matches': '{files} ファイル内に {shown} 件一致', 'search.matches.truncated': '{files} ファイル内の {total} 件中 {shown} 件を表示',
    'search.noResults': '結果がありません', 'search.collapseAria': '結果を折りたたむ', 'search.expandAria': '残り {count} 行の結果を展開',
    'search.expandRest': '… 残り {count} 行', 'web.noResults': '結果が見つかりませんでした', 'web.sourcesTruncated': '情報源の一覧は省略されています',
    'web.http': 'HTTP', 'web.contentTruncated': '内容は省略されています', 'details.running': '実行中…',
    'queue.count': '{n} 件送信待ち', 'queue.sending': '送信中…', 'queue.image': '送信待ちの画像', 'queue.file': '送信待ちのファイル {name}',
    'queue.edit': '送信待ちのメッセージを編集', 'queue.edit.unsupported': 'テキスト以外の内容を含むため編集できません',
    'queue.save': '送信待ちのメッセージを保存', 'queue.cancelEdit': '編集をキャンセル', 'queue.remove': '送信待ちのメッセージを削除',
    'queue.steer': '割り込み送信', 'queue.steer.unavailable': '実行中のみ割り込み送信できます',
    'queue.editFailed': '編集できませんでした。送信が始まっている可能性があります。', 'queue.removeFailed': '削除できませんでした。送信が始まっている可能性があります。',
    'queue.steerFailed': '割り込み送信に失敗しました。再試行してください。', 'terminal.signal': 'シグナル {signal}',
    'terminal.exitCode': '終了コード {code}', 'terminal.running': '実行中', 'terminal.failed': '失敗', 'terminal.done': '完了',
    'terminal.noOutput': '出力なし', 'terminal.collapseAria': '出力を折りたたむ', 'terminal.expandAria': '残り {n} 行の出力を展開',
    'terminal.expandRest': '… 残り {n} 行', 'terminal.sendInput': '（入力を送信）', 'terminal.session': 'ターミナル {sessionId}',
  },
}
