/** Kotoba's paired palette; the existing theme service retains light/dark preference ownership. */
export const palette = {
  '--dsw-alias-bg-base': { light: '#fafcf9', dark: '#111817' },
  '--dsw-alias-bg-layer-1': { light: '#f0f5f0', dark: '#18241e' },
  '--dsw-alias-bg-layer-2': { light: '#e6eee7', dark: '#213128' },
  '--dsw-alias-bg-layer-3': { light: '#d9e5da', dark: '#2b4033' },
  '--dsw-specific-sidebar-fill': { light: '#eef3ed', dark: '#131d18' },
  '--dsw-alias-brand-primary': { light: '#24583c', dark: '#bde6ce' },
  '--dsw-alias-brand-text': { light: '#183e2a', dark: '#ddf1e4' },
  '--dsw-alias-brand-primary-new-colorprimary-new-color': { light: '#34784f', dark: '#9bd5b3' },
  '--dsw-alias-button-primary-fill': { light: '#24583c', dark: '#bde6ce' },
  '--dsw-alias-button-primary-hover': { light: '#1c462f', dark: '#d7f3e1' },
  '--dsw-alias-button-info-fill': { light: '#34784f', dark: '#9bd5b3' },
  '--dsw-alias-button-info-hover': { light: '#24583c', dark: '#bde6ce' },
  '--dsw-alias-label-primary': { light: '#1b3022', dark: '#e3eee7' },
  '--dsw-alias-label-secondary': { light: '#526959', dark: '#a2b9aa' },
  '--dsw-alias-label-tertiary': { light: '#617a6a', dark: '#8ca797' },
  '--dsw-alias-label-primary-foreground': { light: '#f4fcf7', dark: '#153722' },
  '--dsw-alias-border-l2': { light: '#cbdace', dark: '#2d4235' },
  '--dsw-alias-border-l3': { light: '#b8cdbf', dark: '#3a5142' },
  '--dsw-alias-state-business-primary': { light: '#32704b', dark: '#9ad4b2' },
  '--dsw-alias-state-business-tertiary': { light: '#deede2', dark: '#253d2e' },
  '--dsw-specific-sidebar-nav-item-active-accent': { light: '#deede2', dark: '#253d2e' },
  '--dsw-font-family': { light: "'Segoe UI', 'Yu Gothic UI', 'Hiragino Sans', sans-serif", dark: "'Segoe UI', 'Yu Gothic UI', 'Hiragino Sans', sans-serif" },
}
