/** Kotoba's paired palette; the existing theme service retains light/dark preference ownership. */
export const palette = {
  '--dsw-alias-bg-base': { light: '#faf9f6', dark: '#191a1e' },
  '--dsw-alias-bg-layer-1': { light: '#f2f1ed', dark: '#202127' },
  '--dsw-alias-bg-layer-2': { light: '#e8e7e1', dark: '#292b33' },
  '--dsw-alias-bg-layer-3': { light: '#d9e5da', dark: '#343740' },
  '--dsw-specific-sidebar-fill': { light: '#f0efe9', dark: '#15161a' },
  '--dsw-alias-brand-primary': { light: '#24583c', dark: '#c3dacd' },
  '--dsw-alias-brand-text': { light: '#183e2a', dark: '#e9e9ed' },
  '--dsw-alias-brand-primary-new-colorprimary-new-color': { light: '#34784f', dark: '#b2ccbd' },
  '--dsw-alias-button-primary-fill': { light: '#24583c', dark: '#c3dacd' },
  '--dsw-alias-button-primary-hover': { light: '#1c462f', dark: '#d9e8df' },
  '--dsw-alias-button-info-fill': { light: '#34784f', dark: '#b2ccbd' },
  '--dsw-alias-button-info-hover': { light: '#24583c', dark: '#c3dacd' },
  '--dsw-alias-label-primary': { light: '#1b3022', dark: '#e9e9ed' },
  '--dsw-alias-label-secondary': { light: '#526959', dark: '#adafbc' },
  '--dsw-alias-label-tertiary': { light: '#617a6a', dark: '#989bab' },
  '--dsw-alias-label-primary-foreground': { light: '#f4fcf7', dark: '#1b2b22' },
  '--dsw-alias-border-l2': { light: '#cbdace', dark: '#343640' },
  '--dsw-alias-border-l3': { light: '#b8cdbf', dark: '#454854' },
  '--dsw-alias-state-business-primary': { light: '#32704b', dark: '#adc7b8' },
  '--dsw-alias-state-business-tertiary': { light: '#deede2', dark: '#323a38' },
  '--dsw-specific-sidebar-nav-item-active-accent': { light: '#deede2', dark: '#323a38' },
  '--dsw-specific-input-major': { light: '#ffffff', dark: '#24262d' },
  '--dsw-alias-interactive-bg-hover': { light: '#e6e5df', dark: '#30323b' },
  '--dsw-font-family': { light: "'Segoe UI', 'Yu Gothic UI', 'Hiragino Sans', sans-serif", dark: "'Segoe UI', 'Yu Gothic UI', 'Hiragino Sans', sans-serif" },
}
